### ISSUE TITLE
Bug list

### ISSUE THREAD

**Issue by HeicoDev** [goodidea82/SAxVCxLC#17]
High priority

- [x] Bloating save file

- [x] Car generators are being stored to save file

- [ ] Pickups are being stored to save file

Medium priority

- [ ] Several error reports after shooting the gas tank of the car on Nines And Ak's﻿ 

- [ ] Several error reports while near the VC mansion﻿ https://github.com/goodidea82/SAxVCxLC/issues/5

- [ ] Some rooftops in LC are not solid https://github.com/goodidea82/SAxVCxLC/issues/3

- [ ] Some garages in LC do not have a (solid) ground https://github.com/goodidea82/SAxVCxLC/issues/13

- [ ] Under water effect while in tunnels in LC, which are below the water level

- [ ] Several map related issues (gaps, wrong placed objects etc.)

- [ ] Several path related issues (cars spawning in the ground, driving on sidewalk etc.)

Low priority

- [x] Save screen appears after loading a save

- [ ] The zone name appears after diving in water. https://github.com/goodidea82/SAxVCxLC/issues/2

- [ ] xcopcarru is missing in the img files https://github.com/goodidea82/SAxVCxLC/issues/6

- [ ] The basic variant defines map.zon & info.zon https://github.com/goodidea82/SAxVCxLC/issues/4

- [ ] "Teleport to marker" falling trough the map
