### ISSUE TITLE
To-do list [General]

### ISSUE THREAD

**Issue by HeicoDev** [goodidea82/SAxVCxLC#18]
High priority

- [x] Unique data files (.dat) for VC & LC **[WIP by Heico]**

- [ ] Cars & Motorbikes from VC https://github.com/HeicoDev/SAxVCxLC/issues/7 **[WIP by Heico]** 

- [ ] Boats & Aircraft from VC https://github.com/HeicoDev/SAxVCxLC/issues/7

- [ ] Cars & Motorbikes from LC https://github.com/HeicoDev/SAxVCxLC/issues/8 **[WIP]** **[Halted]**

- [ ] Boats & Aircraft from LC https://github.com/HeicoDev/SAxVCxLC/issues/8

- [ ] Peds from VC & LC

- [ ] Weapons from VC & LC

Medium priority

- [ ] Gangs from VC & LC

- [ ] Gang zones for VC & LC

- [ ] Stores, Pay’n’Spray etc.

- [ ] Buyable properties

- [ ] Garages **[WIP by Inan-Ahammad]**

Low priority

- [ ] Cars from VCS & LCS

- [ ] Peds from VCS & LCS

- [ ] Weapons from VCS & LCS

- [ ] Trains for LC

- [ ] Working bridge for LC

- [ ] Missions for VC & LC

- [ ] Map icons from VC & LC
